### ISSUE TITLE
Stop buffer calls start buffer

### ISSUE THREAD

**Issue by d-scanzi** [marcus-nystrom/SMITE#1]
Hi there, 

I was looking at the `stop_buffer` function in SMITE_ET and noticed a couple of things I do not fully understand. The function is defined as:

```python
def stop_buffer(self, clear_buffer=False):
    ''' Stop recording data into buffer
    '''
    self.rawSMI.start_buffer()   
```
Should not this function call `self.rawSMI.stop_buffer()`? Furthermore, the *clear_buffer* argument looks like is not used, or am I missing something?

Thank you for your work!

Have a great day, 

Daniele

**Comment by marcus-nystrom** [comment]
Hi Daniele,

That indeed looks like an error. I have fixed and committed the update.

Thanks,
Marcus
